name: Java CI with Gradle

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Start SUT
        run: |
          echo "Starting the app..."
          java -jar ./artifacts/app-order.jar > app.log 2>&1 &
          sleep 10
          echo "App start command sent"

      - name: Wait for app to be ready
        run: |
          for i in {1..10}; do
            if nc -z localhost 9999; then
              echo "App is ready!"
              exit 0
            fi
            echo "Waiting for app to be ready..."
            sleep 5
          done
          echo "App failed to start on port 9999"
          cat app.log || echo "No log found"
          exit 1

      - name: Build with Gradle
        run: ./gradlew test --info

      - name: Show app.log if tests fail
        if: failure()
        run: |
          echo "========= SUT LOG START ========="
          cat app.log || echo "No app.log found"
          echo "========= SUT LOG END ========="
