name: Java CI with Gradle

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2


      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'


      - name: Grant execute permission for gradlew
        run: chmod +x gradlew


      - name: Start SUT
        run: |
          echo "Starting the app..."
          java -jar ./artifacts/app-order.jar &  
          sleep 10 
          echo "App started"


      - name: Wait for app to be ready
        run: |
          while ! nc -z localhost 9999; do  # Ожидание на порту 9999
            echo "Waiting for app to be ready..."
            sleep 5
          done
          echo "App is ready!"


      - name: Build with Gradle
        run: ./gradlew test --info
